import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <NextTopLoader
          color="#000"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={true}
          easing="ease"
          zIndex={99999}
          speed={200}
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
        />

        <Header></Header>
        <main className="pt-[80px]">{children}</main>
      </body>
    </html>
  );
}
